# This is a basic workflow to help you get started with Actions

name: Resusale Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      repo_owner:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  RepoB-Job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
      - name: run remote workflow
        uses: whsalazar-org/workflow-dispatcher@master
        with:
          owner: ${{ inputs.repo_owner }}
          repo: ${{ inputs.repo_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          event_type: LOCALRUN
          client_payload: '{"git-ref": "${{ github.event.inputs.git-ref }}"}'
          wait_time: 5
          max_time: 180
          
  RepoB-Job4: 
     needs: [RepoB-Job2]
     uses: ./.github/workflows/workflow-2.yml
